### ISSUE TITLE
Reproducible script requirements

### ISSUE THREAD

**Issue by liruiluo** [AlignmentResearch/vlmrm#4]
This is really a great work
I tried changing the parameters in config.yaml, but still can't get any meaningful movements in Humanoid. Can you provide a reproducible script? Thanks a lot!

**Comment by Rocamonde** [comment]
Thanks! A few people have also privately asked for examples of run cards, so will aim to upload all our run data exports from wandb (which includes the run data / params etc.) over the next few days and link it to the repo.

**Comment by liruiluo** [comment]
Now I have a new problem: the results obtained each time I run the script are different, even though the random seed has been determined. How can I solve this problem?

**Comment by Rocamonde** [comment]
All run data can be found here: https://drive.google.com/drive/folders/1E6PomaFeCOUPSbkTpwmJI1Hz51e_47yM?usp=drive_link

Regarding randomization, you want to make sure you're seeding all sources of entropy, including numpy. Could you provide a reproducible example where you're getting different results on different runs? So that I can provide more input on how to address this.
